# Reference: https://github.com/repository-settings/app

_extends: .github

repository:
  name: sar-template
  description: Publish and share Organization wide Cloudformation templates using the Serverless Application Repository (SAR).
  topics: aws, sar, example
  private: false
  has_issues: true
  has_projects: true
  has_discussions: false

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage

environments:
  - name: production

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Test
