AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Example SAR application for cross-org sharing

Parameters:
  Name:
    Type: String
    Description: The name of the example bucket to create
    AllowedPattern: ^[a-z0-9-]+$

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mytiki-sar-template
    Description: Example SAR application for cross-org sharing
    Author: mytiki
    SpdxLicenseId: AGPL-3.0-or-later
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['sar', 'example']
    HomePageUrl: https://github.com/tiki-bar/sar-template
    SemanticVersion: ${Version}
    SourceCodeUrl: https://github.com/tiki-bar/sar-template

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Name
